Lecture 1 setup and product dao
froggypol/phoneshop-servlet-api pull request #1
Opened 2019-10-27 17:59 UTC by froggypol

2019-10-28 07:38 UTC, Alastifer requested changes

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +import java.util.*;
wildcard не юзаем

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    List<Product> productListDaoSynchronized;
Зачем тебе два листа для хранения?

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    List<Product> productListDaoSynchronized;
Почему они не приватные?

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    List<Product> productListDaoSynchronized;
Пустых строк нет. Все слиплось

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        save(new Product((long)productListDao.size()+1, "simsxg75", "Siemens SXG75", new BigDecimal(150), usd, 40, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufa
Добавление через вызов add в листе, а не через save

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productListDaoSynchronized.addAll(Collections.synchronizedList(productListDao));
Давай будем делать свою синхронизацию, не использую synchronizedList

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            return product;
getProduct должен возвращать Optional

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                e.printStackTrace();
эксепшены так никогда не кидают

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            return product;
Форматирование кода поехало

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    public Product getProduct(Long id){
пробел между ) и {

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        save(new Product((long)productListDao.size()+1, "sgs", "Samsung Galaxy S", new BigDecimal(100), usd, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufac
id тут просто попорядку добавляй (1, 2, 3)

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +         return result;
уехал код

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        ArrayList<Product> result = new ArrayList<>();
зачем тебе этот лист? юзай Collectors в стриме

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        product.setId((long)productListDaoSynchronized.size()+1);
используй UUID для генераци id

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productListDaoSynchronized.add(product);
что будет, если продукт передается уже с id?

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productListDaoSynchronized.addAll(result);
очень стремный способ удалить. indexOf и set юзай

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
>      }
зачем нам этот метод?

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
оставь либо код, либо id. Лучше конечно код, потому что генерить через UUID будешь

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    }
почитай как нужно делать инит метод в сервлете

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    ArrayListProductDao productListDao;
почему не private?

2019-10-28 07:38 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        return productListDao.getProductListDao();
у тебя есть findProducts

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +import static org.junit.Assert.*;
wildcard не используем

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertFalse("Empty product list, sorry", productDao.findProducts().isEmpty());
сообщения не нужны

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      public void testFindProductsNoResults() {
именование у тестов должно быть такое: результатWhenКакое-тоДействие

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    }
в тестах эксепшены не ловят

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void testGetProductIdWrongResults(){
форматирование

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void testDeleteProductError(){
форматирование

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void testSaveProductError(){
форматирование

2019-10-28 07:38 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
>          verify(requestDispatcher).forward(request, response);
проверь есть ли продукты в реквесте

2019-10-28 17:00 UTC, froggypol commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    List<Product> productListDaoSynchronized;
При новых объявлениях надо пустые строки добавить?

2019-10-28 17:25 UTC, froggypol commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
Если удаляю поле id, то для UUID использовать генерацию ключа через название продукта можно  сделать ведь?

2019-10-29 08:01 UTC, froggypol commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productListDaoSynchronized.add(product);
тогда мне нужны два поля: и code, и id. на основе кода я буду генерить айди, если добавляется новый продукт, а если у меня добавляется продукт уже с заполненным айдишником, то просто перезаписать
т.к. при удалении одного их полей у меня не будет возможности генерировать уникальные ключи

2019-10-29 10:02 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productListDaoSynchronized.add(product);
так ты оставь либо code, либо id

2019-10-29 10:03 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
так uuid же вроде не требует никаких параметров

2019-10-29 10:32 UTC, froggypol commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
Я генерирую через поле description: UUID uuid = UUID.fromString(description);

2019-10-29 10:53 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
randomUUID()

2019-10-29 10:55 UTC, froggypol commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
Тогда у меня для одинаковых продуктов буду разные айди
И будет список с дубликатами

2019-10-29 11:21 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID()

2019-10-29 11:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
> Тогда у меня для одинаковых продуктов буду разные айди
> И будет список с дубликатами

всмысле? что по твоему разные продукты? для меня это продукты с разными id

2019-10-29 12:00 UTC, froggypol commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
Поняла, как это можно сделать. Спасибо)

2019-11-10 09:14 UTC, Alastifer requested changes

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +    private static List<Product> productListDao;
окончание переменных - их реальное назвачение. Для меня это дао, а не лист, каким он и должен являться. переименуй в productList

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +            }
зачем тут логика на проверку существования? в дао этой логики быть не должно

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +                    .collect(Collectors.toCollection(ArrayList::new));
есть метод toList

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +            return productListDao.stream().filter(product -> product.getStock() > 0 && !product.getPrice().equals(BigDecimal.ZERO))
steam() а затем с новой строки

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +            productListDao = productListDao.stream().filter(s -> !s.getId().equals(id)).collect(Collectors.toList());
stream()
.filter
.collect

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +                    });
переведи массив в стрим. Погугли

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +    }
сетер так не юзается

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/DaoProductListListener.java
> +        singletonProductList.save(new Product("Siemens SXG75", new BigDecimal(150), usd, 40, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Siemens/Siemens
давай перенесем это в getInstance дао

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/synchronization/object/SynchronizedObject.java
> +    private Map<String, Product> productPool = new HashMap<>();
String и объект по которому будет синхронизировать. Это не продукт сам

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/AjaxSortingOnDescription.java
> +public class AjaxSortingOnDescription extends HttpServlet {
в конце в имени должно быть Servlet

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Sort.java
> +                : getSortedListForPrice(listToSort, orderToSort);
equals ?
one :
two;

2019-11-10 09:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Sort.java
> +                (prod2.getDescription().compareTo(prod1.getDescription()))).collect(Collectors.toList());
выглядет слипшейся

2019-11-10 09:14 UTC, Alastifer commented on src/main/webapp/WEB-INF/web.xml
> +        <url-pattern>/products/ajax</url-pattern>
url норм напиши

2019-11-10 09:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/CustomProductDaoTest.java
> +        listProducts = productDao.setProductList();
сеттер это не геттер

2019-11-10 09:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/CustomProductDaoTest.java
> +public class CustomProductDaoTest {
ты тестируешь используя данные из дао. Так нельзя делать. Нужно в тесте всё сетать

2019-11-10 09:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/tests/service/ProductServiceDaoTest.java
> +public class ProductServiceDaoTest {
Service и DAO - разные вещи

2019-11-10 09:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/tests/service/ProductServiceDaoTest.java
> +        productList = CustomProductDao.getInstance();
дао мокам делать

2019-11-10 09:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/AjaxSortingServletTest.java
> +public class AjaxSortingServletTest {
имя еста - это название класса, который ты тестишь + Test

2019-11-10 09:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductDetailsPageServletTest.java
> +    public void whenDoGetError() throws ServletException, IOException {
именование

2019-11-10 09:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
> -        servlet.doGet(request, response);
именование

2019-11-10 16:29 UTC, Alastifer requested changes

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
>                  }
В дао нет опработок optional. Это всё должен сервис делать

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +                                     .filter(s -> !s.getId().equals(id))
более конкретное имя переменной

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +                Supplier<Stream<String>> streamSupplier = () -> Stream.of(list);
форматирование

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +                Supplier<Stream<String>> streamSupplier = () -> Stream.of(list);
Arrays.stream(array)

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Sort.java
> +                                    .collect(Collectors.toList());
вынеси в отдельный метод и просто передавай туда способ сортировки

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Sort.java
> +                                    .collect(Collectors.toList());
тоже самое что и выше

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/com/es/phoneshop/synchronization/object/SynchronizedObject.java
> +    private Map<String, Object> productPool = new HashMap<>();
ну наверное тогда нужно попереименовать всё) а то продукты везде

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/service/ProductService.java
> +        return productDaoService.getProductById(id).isPresent() ? productDaoService.getProductById(id).get() : null;
форматирование

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/service/ProductService.java
> +        return productDaoService.getProductById(id).isPresent() ? productDaoService.getProductById(id).get() : null;
если продукта нет, то в сервисах кидается exception и отлавливается в сервлете

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/service/ProductService.java
> +    public CustomProductDao getCustomProductDao(){
форм

2019-11-10 16:29 UTC, Alastifer commented on src/main/java/service/ProductService.java
> +    public void setCustomList(List<Product> toSet){
форм

2019-11-10 16:29 UTC, Alastifer commented on src/main/webapp/WEB-INF/web.xml
> +        <url-pattern>/products/*</url-pattern>
я имел ввиду /products/sort. Сама подумай к чему твой маппинг приведет

2019-11-10 16:29 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/CustomProductDaoTest.java
> +    private CustomProductDao customProductList;
причем тут list?

2019-11-12 10:23 UTC, Alastifer requested changes

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +    private static List<Product> productListDao;
измени имя

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +        synchronized (new SynchronizedObject(id)) {
может лучше сделать статик метод. Типа SynchronizedObject.getBlockObject(id)

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +                        .filter(prod -> prod.getId().equals(id)).findFirst();
stream()
.filter
.findFirst

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +                        .filter(prod -> prod.getId().equals(id)).findFirst();
и лучше findAny

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +        synchronized (this) {
нужна ли здесь синхронизаиця?

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +        synchronized (new SynchronizedObject(productName)) {
нужна ли тут синхронизация?

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/DaoProductListListener.java
> +}
нужен один лиснер где инициализируется дао и сервис

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Sort.java
> +                               .collect(Collectors.toList());
вынеси

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Sort.java
> +                              .collect(Collectors.toList());
вынеси

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/synchronization/object/SynchronizedObject.java
> +            objectPool.put(UUID.randomUUID().toString(), object);
зачем новую id генерить?

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/AjaxSortingServlet.java
> +        out.close();
поразделяй пустыми строками немного

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +    private static CustomProductDao productListSingleton;
назови просто productDao

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +        productList.add(new Product("Siemens SXG75", new BigDecimal(150), usd, 40, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Siemens/Siemens%20SXG75.j
в отдельный метод

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/CustomProductDao.java
> +            productList = new ArrayList<>();
это не нужно

2019-11-12 10:23 UTC, Alastifer commented on src/main/java/service/ProductService.java
> +        return productDaoService.getProductById(id).get();
если продукт не найдет, то нужно кидать кастомный эксепшн и ловить его в сервлете

2019-11-12 10:23 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
> +import static org.mockito.Mockito.*;
wildcard убери

2019-11-13 08:28 UTC, merged